kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 4dqrtlljnTHVLBQ4GSYYUXpgP1WMcdK8sR/A2yGfMtw=
      - identity: {}
