kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: umrd05718bgTogtBwgxVczP/eXJN6wL2q1gk1757tUg=
      - identity: {}
