kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: uMOW18dUjy5PWVIMZ41d7zGjU+6xOL5njPicOwpbrmA=
      - identity: {}
