kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 73b8smi49NI34d7GKRd/GY0fEf9xjV48AvN6OWG3OpY=
      - identity: {}
