kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: XSZrWylgpCQBcVvpD58BIsEq54+DVXD2aV08SViCBaE=
      - identity: {}
